import { Inter } from 'next/font/google';
import './globals.css';
import { CssBaseline } from '@mui/material';
import ResponsiveAppBar from '@/component/ResponsiveAppBar';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import { AuthProvider } from '@/contexts/authContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Manager',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CssBaseline />

      <meta name="viewport" content="initial-scale=1, width=device-width" />

      <body className={inter.className}>
        <AuthProvider>
          <ResponsiveAppBar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
